// <auto-generated />
using System;
using EphemerisHub.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EphemerisHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250703133118_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EphemerisHub.Models.RinexBeidouEphemeris", b =>
                {
                    b.Property<int>("SatellitePrn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOfClock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Aodc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Aode")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("BdtWeek")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cic")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cis")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockBias")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDrift")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDriftRate")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Crc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Crs")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cuc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cus")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaN")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Eccentricity")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("I0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Idot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("M0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("OmegaDot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SatH1")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<string>("SatelliteSystem")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<double>("Spare1")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Spare2")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SqrtA")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SvAccuracy")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Tgd1")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Tgd2")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Toe")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("TransmissionTime")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.HasKey("SatellitePrn", "TimeOfClock");

                    b.ToTable("BeidouEphemeris");
                });

            modelBuilder.Entity("EphemerisHub.Models.RinexGalileoEphemeris", b =>
                {
                    b.Property<int>("SatellitePrn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOfClock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("BgdE5aE1")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("BgdE5bE1")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cic")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cis")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockBias")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDrift")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDriftRate")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Crc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Crs")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cuc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cus")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("DataSources")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaN")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Eccentricity")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("GalWeek")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("I0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Idot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Iodnav")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("M0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("OmegaDot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<string>("SatelliteSystem")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<double>("Sisa")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Spare")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SqrtA")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SvHealth")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Toe")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("TransmissionTime")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.HasKey("SatellitePrn", "TimeOfClock");

                    b.ToTable("GalileoEphemeris");
                });

            modelBuilder.Entity("EphemerisHub.Models.RinexGlonassEphemeris", b =>
                {
                    b.Property<int>("SatellitePrn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOfClock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("AccX")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("AccY")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("AccZ")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("AgeOfOperation")
                        .HasColumnType("double precision");

                    b.Property<double>("ClockBias")
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDrift")
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDriftRate")
                        .HasColumnType("double precision");

                    b.Property<double>("FreqNum")
                        .HasColumnType("double precision");

                    b.Property<double>("Health")
                        .HasColumnType("double precision");

                    b.Property<double>("PosX")
                        .HasPrecision(15, 3)
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasPrecision(15, 3)
                        .HasColumnType("double precision");

                    b.Property<double>("PosZ")
                        .HasPrecision(15, 3)
                        .HasColumnType("double precision");

                    b.Property<string>("SatelliteSystem")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<double>("VelX")
                        .HasPrecision(15, 9)
                        .HasColumnType("double precision");

                    b.Property<double>("VelY")
                        .HasPrecision(15, 9)
                        .HasColumnType("double precision");

                    b.Property<double>("VelZ")
                        .HasPrecision(15, 9)
                        .HasColumnType("double precision");

                    b.HasKey("SatellitePrn", "TimeOfClock");

                    b.ToTable("GlonassEphemeris");
                });

            modelBuilder.Entity("EphemerisHub.Models.RinexGpsEphemeris", b =>
                {
                    b.Property<int>("SatellitePrn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOfClock")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Cic")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cis")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockBias")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDrift")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("ClockDriftRate")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("CodesOnL2")
                        .HasColumnType("double precision");

                    b.Property<double>("Crc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Crs")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cuc")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Cus")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaN")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Eccentricity")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("FitInterval")
                        .HasColumnType("double precision");

                    b.Property<double>("GpsWeek")
                        .HasColumnType("double precision");

                    b.Property<double>("I0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Idot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Iodc")
                        .HasColumnType("double precision");

                    b.Property<double>("Iode")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("L2PDataFlag")
                        .HasColumnType("double precision");

                    b.Property<double>("M0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("Omega0")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("OmegaDot")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<string>("SatelliteSystem")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<double>("SqrtA")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("SvAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("SvHealth")
                        .HasColumnType("double precision");

                    b.Property<double>("Tgd")
                        .HasColumnType("double precision");

                    b.Property<double>("Toe")
                        .HasPrecision(15, 12)
                        .HasColumnType("double precision");

                    b.Property<double>("TransmissionTime")
                        .HasColumnType("double precision");

                    b.HasKey("SatellitePrn", "TimeOfClock");

                    b.ToTable("GpsEphemeris");
                });
#pragma warning restore 612, 618
        }
    }
}
